alias ll='ls -altr'
alias gs='git status'
alias gd='git diff'
alias sshpi1='ssh pi@172.16.2.101'
alias sshpi2='ssh pi@172.16.2.102'
alias sshnas='ssh avi@172.16.1.10'
alias nagios-conf='cd /etc/nagios3/conf.d'
alias nagios-plugins='cd /usr/lib/nagios/plugins'
alias telegram-bot='cd /home/pi/git_repos/telegram-bot'
alias dotfiles='cd /home/pi/dotfiles'

